### ISSUE TITLE
BadSignature in Starlette: Stray Cookies Problem

### ISSUE THREAD

**Issue by dannmartens** [jordanisaacs/fastapi-sessions#6]
When I tried your test app in a browser, using a small form POSTing from an HTML page, I got:
```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/devs/.local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 398, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/devs/.local/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/home/devs/.local/lib/python3.8/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/home/devs/.local/lib/python3.8/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/devs/.local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/devs/.local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/devs/.local/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/devs/.local/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/devs/.local/lib/python3.8/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/home/devs/.local/lib/python3.8/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/home/devs/.local/lib/python3.8/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/home/devs/.local/lib/python3.8/site-packages/fastapi/routing.py", line 191, in app
    solved_result = await solve_dependencies(
  File "/home/devs/.local/lib/python3.8/site-packages/fastapi/dependencies/utils.py", line 548, in solve_dependencies
    solved = await call(**sub_values)
  File "./fastapi_sessions/session_cookie.py", line 60, in __call__
    session_id = self.signer.loads(
  File "/home/devs/.local/lib/python3.8/site-packages/itsdangerous/timed.py", line 142, in loads
    raise last_exception
  File "/home/devs/.local/lib/python3.8/site-packages/itsdangerous/timed.py", line 130, in loads
    base64d, timestamp = signer.unsign(s, max_age, return_timestamp=True)
  File "/home/devs/.local/lib/python3.8/site-packages/itsdangerous/timed.py", line 66, in unsign
    raise sig_error
  File "/home/devs/.local/lib/python3.8/site-packages/itsdangerous/timed.py", line 52, in unsign
    result = Signer.unsign(self, value)
  File "/home/devs/.local/lib/python3.8/site-packages/itsdangerous/signer.py", line 165, in unsign
    raise BadSignature("No %r found in value" % self.sep)
itsdangerous.exc.BadSignature: No b'.' found in value
```

But when I tried it with a REST tool, POSTing bare:
```
POST http://localhost:8080/get_session?username=me HTTP/1.1
```

I got:
```
HTTP/1.1 200 OK
date: Wed, 16 Jun 2021 19:10:53 GMT
server: uvicorn
content-length: 61
content-type: application/json
set-cookie: session=IlhqMWJHVDh3TGN3dmpoc1BRTU1iTWJkcUdCeXdBWWtrdDVGNFZUZk9LVXBOcUVJeVNMd0xXak9iUkVaeXBQcWp0TFF5MndBaW5GUFI4UzJsU1l6RE9RPT0i.YMpMvg.pd7FEmWVm5qoLLoN4u_B4Fj-ciU; HttpOnly; Max-Age=1209600; Path=/; SameSite=lax,sessioncsrf=IjZlQk8ySTFGNm9scEdGYUpUc0padUg0VE5kK0JSSm9FNjc5d1BheHN0d3FxSW92c1I5MktwZTB4YTFoZUFVRXNDSFMwQmRSSTZLMGZ4Vi9UWStCYU1RPT0i.YMpMvg.e4XSw91UPMK2wPSROGn1ALZ9pv4; Path=/; SameSite=lax
connection: close

{
  "message": "You now have a session",
  "user": {
    "username": "me"
  }
}
```

I checked what was causing this, and apparently, when I add a stray cookie, it crashes as it does above:
```
POST http://localhost:8088/get_session?username=me HTTP/1.1
Cookie: session=868f48a7-1a58-4a85-8bf1-b94153b69a25
```

It would appear that a stray cookie, e.g. from another app under development, isn't handled right yet.

**Comment by dannmartens** [comment]
I managed to trigger the same error in a standalone Starlette application, with the built-in SessionMiddleware enabled.

The reason is the same: the session cookie already exists, but it's invalid. 

It happens in: https://github.com/encode/starlette/blob/15761fb48e4c56be09167cb8f9b761114593b651/starlette/middleware/sessions.py#L41-L45

BadSignature is not named in the except clause, causing the server to HTTP 500.

**Comment by jordanisaacs** [comment]
Hi, sorry for the slow response. Been extremely busy personally the last month. Check out this [issue](https://github.com/jordanisaacs/fastapi-sessions/issues/7) for a general response and goals for a rewrite.
